services:
  rtsp_stream_recorder:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rtsp_stream_recorder
    restart: always
    env_file: .env
    volumes:
      - ./data:/app/data
